Revert "Mitigate CVE-2018-1199"
This reverts commit 537c398d764de263f9b1675aeeab7e5b1314f5af.

Otherwise MutableLogoutFilterSpec fails with:

org.springframework.util.AntPathMatcher.setCaseSensitive(Z)V
java.lang.NoSuchMethodError: org.springframework.util.AntPathMatcher.setCaseSensitive(Z)V
	at org.springframework.security.web.util.matcher.AntPathRequestMatcher$SpringAntMatcher.createMatcher(AntPathRequestMatcher.java:268)
	at org.springframework.security.web.util.matcher.AntPathRequestMatcher$SpringAntMatcher.<init>(AntPathRequestMatcher.java:252)
	at org.springframework.security.web.util.matcher.AntPathRequestMatcher$SpringAntMatcher.<init>(AntPathRequestMatcher.java:245)
	at org.springframework.security.web.util.matcher.AntPathRequestMatcher.<init>(AntPathRequestMatcher.java:116)
	at org.springframework.security.web.util.matcher.AntPathRequestMatcher.<init>(AntPathRequestMatcher.java:84)
	at org.springframework.security.web.util.matcher.AntPathRequestMatcher.<init>(AntPathRequestMatcher.java:72)
	at org.springframework.security.web.authentication.logout.LogoutFilter.setFilterProcessesUrl(LogoutFilter.java:143)
	at org.springframework.security.web.authentication.logout.LogoutFilter.<init>(LogoutFilter.java:78)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.<init>(MutableLogoutFilter.groovy:53)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilterSpec.$spock_initializeFields(MutableLogoutFilterSpec.groovy:38)

        at org.springframework.security.web.authentication.logout.LogoutFilter.setFilterProcessesUrl(LogoutFilter.java:143)
        at org.springframework.security.web.authentication.logout.LogoutFilter.<init>(LogoutFilter.java:78)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.<init>(MutableLogoutFilter.groovy:53)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilterSpec.$spock_initializeFields(MutableLogoutFilterSpec.groovy:38)