Update to Grails 6 (#915)
* Update to Grails 6

* Update build.gradle

* Fix java.lang.NoClassDefFoundError: org/openqa/selenium/interactions/HasTouchScreen

* Force selenium version